### ISSUE TITLE
Advise deployments to support a global HPKE config if in-band task provisioning is supported

### ISSUE THREAD

**Issue by junyechen1996** [wangshan/draft-wang-ppm-dap-taskprov#11]
If a deployment supports in-band task provisioning, then clients should not query `/hpke_config` with a specified `task_id`. The reason is:

1. Aggregators need the first client report for a particular TaskID, in order for the task to be configured.
2. Clients need the HPKE config to submit reports. If `task_id` parameter is included when clients query `/hpke_config` endpoint, the Aggregator may not know that TaskID yet, because it has not received any report for that.

One way is to advise deployment to support a global HPKE config, and also advise clients to not pass `task_id` to `/hpke_config` endpoint. The other way is to create the HPKE config on the fly for unseen task ID in `/hpke_config`.

**Comment by cjpatton** [comment]
Yup 👍

**Comment by cjpatton** [comment]
@junyechen1996 we just merged #9  so this would be a good time for text

**Comment by junyechen1996** [comment]
Addressed by https://github.com/wangshan/draft-wang-ppm-dap-taskprov/pull/21
