### ISSUE TITLE
Decoding unrecognized message variants

### ISSUE THREAD

**Issue by cjpatton** [wangshan/draft-wang-ppm-dap-taskprov#23]
The following messages have contents for which decoding depends on an `enum`:
- VdafConfig (need to know the VdafType in order to decode the rest of the message)
- DpConfig (need to know the DpMechanism in order to decode the rest of the message)
- QueryConfig (need to know the QueryType in order to decode everything after min_batch_size)

What do we do if we get a variant we don't recognize? How do we decode the rest of the message? The answer is we can't, since we don't know how many more bytes to consume. All we can do in taskprov-00 is abort with "unrecgonizedMessage", since we don't know how to parse.

Question 1: Is this the intended behavior? Or would it be better "opt-out" by aborting with "invalidTask"?

Regardless of the answer for taskprov-00, I think for the next version (taskprov-01) we ought to make sure messages can always be decoded, regardless of whether we know how to handle the parameters. The easiest way to do this would be to add a length prefix so that the contents can be handled as opaque blobs. This might look something like this (I'll have to double check if this is valid syntax; a similar situation arises in the TLS 1.3 record layer):

```
struct {
       DpConfig dp_config;
       VdafType vdaf_type;
+      uint16_t vdaf_param_len;
       select (VdafConfig.vdaf_type) {
           case prio3_aes128_count: Empty;
           case prio3_aes128_sum: uint8; /* bit length of the summand */
           case prio3_aes128_histogram: uint64<8..2^24-8>; /* buckets */
           case poplar1_aes128: uint16; /* bit length of input string */
+          default: opaque[VdafConfig.vdaf_param_len];
       }
   } VdafConfig;
```

This came up while reviewing changes for Daphne: https://github.com/cloudflare/daphne/pull/148#discussion_r1001182181.

**Comment by junyechen1996** [comment]
Won't this problem also exist for DAP as well, e.g. enums like `QueryType` and `PrepareStepResult` are needed to decode the rest of the messages? Is the concern that there is no text to recommend what kind of error an aggregator should abort with?

In DAP, I don't seem to find any recommendation for `unrecognizedMessage` when an enum value is an unknown variant. Could you point me to those if there is any?

**Comment by cjpatton** [comment]
Fair point, but I think it's more of a problem here than for core DAP:
- (defined in DAP) PrepareStepResult is really quite core DAP, so we don't expect variants to be defined outside of DAP. The spec should say unrecognizedMessage on unknown variant (probably a good idea to make this explicit).
- (defined in DAP) QueryType: I guess I can variants being defined outside the core protocol, but it seems somewhat unlikely, given how invasive new query types might be.
- (defined here) DpMechanism: I'm not sure, but I suspect we'll have a few variants of this. Ideally they would all be defined in this spec?
- (defined here) VdafType: We expect to have lots of variants of this, and I don't expect that all variants in the wild will be defined here.

**Comment by junyechen1996** [comment]
I see, so I guess the concern is this draft doesn't have a clear guidance on what error each entity should throw when encountering an unknown enum.

Regarding `DpMechanism`, it has implications on how DP noise is added on each entity (client or aggregator), we still need to define this better, but an entity in a deployment may not support all DP mechanisms, so it seems like it should opt out of the task if it cannot support a particular DP mechanism?
Regarding `VdafType`, an entity may not know about all the VDAFs either, so it seems like it should opt out of the task as well?

**Comment by cjpatton** [comment]
> Regarding `DpMechanism`, it has implications on how DP noise is added on each entity (client or aggregator), we still need to define this better, but an entity in a deployment may not support all DP mechanisms, so it seems like it should opt out of the task if it cannot support a particular DP mechanism?

I agree.

> Regarding `VdafType`, an entity may not know about all the VDAFs either, so it seems like it should opt out of the task as well?

Yes I think so.

In both cases, in taskprov-00 we'll have to abort with "unrecog nizedMessage". I think what we actually want is to abort with "invalidTask". In particular, in taskprov-01 we should:

1. Makes sure DpConfig and VdafConfig can always be parsed even if the variant is not recognized.
2. Say each protocol participant MUST opt-out if they don't recognize DP mechanism or VDAF type

**Comment by junyechen1996** [comment]
I'm not sure about this requirement:

> Makes sure DpConfig and VdafConfig can always be parsed even if the variant is not recognized.

Won't DAP face this issue as well? For example, `PrepareStepResult` is an unrecognized enum (helper just sends this back intentionally), the rest of `PrepareStep` can't be parsed.

**Comment by cjpatton** [comment]
Again, I think the concern for PrepareStepResult is not comparable because we don't expect new variants of PrepareStep to appear in the wild.

**Comment by junyechen1996** [comment]
I think I see the motivation better after our discussion about an unknown `DpMechanism` in `VdafConfig`... so an aggregator can parse the whole `TaskConfig`, but then decide whether it should opt in or out of the task. For example, even though an aggregator doesn't know what `DpMechanism` that is, it can still run the VDAF (because it may not need the `DpMechanism`), so the aggregator may still opt into the task?

**Comment by cjpatton** [comment]
That's a really good point. If I don't recognize the VDAF, then there is nothing I can do but opt out; but if I don't recognize the DP mechanism, it's possible that I'm actually supposed to ignore it. But how would I know that, unless I know the mechanism?

**Comment by junyechen1996** [comment]
> If I don't recognize the VDAF, then there is nothing I can do but opt out;

Certainly.

> if I don't recognize the DP mechanism, it's possible that I'm actually supposed to ignore it. But how would I know that, unless I know the mechanism?

I don't have a clear answer to this to be honest :) because DP is still vaguely defined in the DAP/VDAF context as of today. An unknown `DpMechanism` may not matter to an aggregator when it executes the VDAF, because some VDAFs may choose to only ask clients to add local DP, so there is no need for aggregators to add DP, if minimum batch size is already met. In fact, in Prio2 or Prio3Aes128CountVec, there is no guidance on how central DP is applied yet. A task "Author" simply logs the `DpMechanism` for transparency reasons, so clients are aware of what kind of overall DP guarantee they can get by participating in the task.

**Comment by cjpatton** [comment]
I would suspect that, even if the DP mechanism is entirely local to the client, an aggregator may wish to opt-out if it decides the degree of privacy that is provided is too low. Of course, this decision process is beyond the scope of this document. The main thing here is to separate "I don't know how to parse this" from "I don't know what to do with this".

**Comment by wangshan** [comment]
will address this once https://github.com/wangshan/draft-wang-ppm-differential-privacy/blob/main/draft-wang-ppm-differential-privacy.md is in a good shape.

**Comment by cjpatton** [comment]
@wangshan I'd like to fix this before we cut the next draft. It's currently a bit of a headache. I'll propose some text.

**Comment by wangshan** [comment]
@cjpatton just so I understand, the goal here is to make sure if any struct inside TaskConfig is unrecognised, the aggregator can still parse the rest of TaskConfig and decide what to do?

**Comment by cjpatton** [comment]
Precisely!

**Comment by suman-ganta** [comment]
```
default: opaque[VdafConfig.vdaf_param_len];
```
The [RFC](https://datatracker.ietf.org/doc/html/rfc8446#section-3.8) doesn't define the following - a) `default` keyword b) non-literal vector length.
An alternative is to drop `select` construct from the structure altogether and interpret the opaque byte array at runtime based on value of enum.

**Comment by cjpatton** [comment]
Hey @suman-ganta, a comment on an already merged PR is easy to miss. I suggest raising an issue to discuss.
