### ISSUE TITLE
Leader cannot usefully set `Retry-After` in collection req responses

### ISSUE THREAD

**Issue by tgeoghegan** [wangshan/draft-wang-ppm-dap-taskprov#35]
The "Collect Protocol" section currently reads:

> The Collector might issue a collect request for a task provisioned by the Taskprov extension prior to opting in to the task. In this case, the Leader would need to abort the collect request with "unrecognizedTask". When it does so, it SHOULD also include a "Retry-After" header in its HTTP response indicating the time after which the Collector should retry its request.

The collection job creation request will fail until a Client does an upload that contains a `dap-taskprov` header corresponding to the task ID. The Leader has no way to know when a Client will get around to doing that, so there's really nothing useful it can set as the value to the `Retry-After` header.

If the intent is to allow Leaders to rate limit Collectors, then I'd argue that is not DAP or taskprov's problem: a DAP Leader is an HTTP server and thus is free to use any rate-limiting mechanism that's composable with HTTP without requiring special permission from the application protocol.

**Comment by wangshan** [comment]
@tgeoghegan I think the intention is to allow Leader to tell collector whether the requested task hasn't been created yet (in which case collector should retry), or there is a mismatch between of taskConfig. But I think your point is valid:

>  a DAP Leader is an HTTP server and thus is free to use any rate-limiting mechanism that's composable with HTTP without requiring special permission from the application protocol.

We can either change the `SHOULD` to `MAY`, or remove the retry-after option

**Comment by cjpatton** [comment]
I'd opt for removing the retry-after to simplify the spec.
