### ISSUE TITLE
Update histogram representation for VDAF-06

### ISSUE THREAD

**Issue by tgeoghegan** [wangshan/draft-wang-ppm-dap-taskprov#36]
Taskprov currently has:
```
struct {
    DpConfig dp_config;
    VdafType vdaf_type;
    select (VdafConfig.vdaf_type) {
        case prio3_aes128_count: Empty;
        case prio3_aes128_sum: uint8; /* bit length of the summand */
        case prio3_aes128_histogram: uint64<8..2^24-8>; /* buckets */
        case poplar1_aes128: uint16; /* bit length of input string */
    }
} VdafConfig;
```

In VDAF-06, rather than taking a list of bucket boundaries, the `Prio3Histogram` VDAF just takes a length, which is the number of buckets.

Additionally, all these VDAF names have `aes128` in them, which is also obsolete.

**Comment by cjpatton** [comment]
This mostly duplicates https://github.com/wangshan/draft-wang-ppm-dap-taskprov/issues/33.

**Comment by tgeoghegan** [comment]
Oops, I should have checked for existing issues! Please feel free to close this in favor of #33.
