### ISSUE TITLE
Separate transparency technique from in-line provisioning

### ISSUE THREAD

**Issue by simon-friedberger** [wangshan/draft-wang-ppm-dap-taskprov#54]
https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/500 was closed reasoning that the transparency problem can be solved by taskprov. @cjpatton suggested to split taskprov to enable using the transparency part without in-line provisioning.

**Comment by cjpatton** [comment]
Thanks Simon. Based on the feedback from IETF 118 I think we definitely need to implement this.

First, we need to be very careful with the word "transparency". Taskprov does not provide transparency in the sense of "Certificate Transparency" or the newly formed Key Transparency WG at IETF. Instead what we get is a property we might call **task binding**: _Correct execution of a task implies agreement on the task config_. (Conversely, disagreement on the config implies abort.)

I'd like to suggest the following rework. There will be two major sections.

The first section would describe how task binding works. In particular it would define `TaskConfig` and describe how to compute the task ID.

The second section would describe the `taskprov` report extension and attendant behavior changes. It would also describe deriving the VDAF verify key.
