### ISSUE TITLE
Consider renaming leader_url and helper_url

### ISSUE THREAD

**Issue by cjpatton** [wangshan/draft-wang-ppm-dap-taskprov#6]
Deployments may end up putting place holders here or doing something else.

**Comment by wangshan** [comment]
@cjpatton can we close this one? I don't see leader_url/helper_url in the spec anymore

**Comment by cjpatton** [comment]
Actually we need to align these with DAP-07: https://github.com/wangshan/draft-wang-ppm-dap-taskprov/pull/44 should close this.
